name: Refresh data

on:
  workflow_dispatch: {}
  schedule:
    # 09:17 UTC ≈ 02:17 PT (adjust if you want)
    - cron: "17 9 * * *"

permissions:
  contents: write   # needed to push the refreshed JSON

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: refresh-data
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch headshots (optional)
        run: node scripts/get-photos.mjs || true

      # if package.json is optional in this repo, keep the || true
      - name: Install (best effort)
        run: npm ci || true

      # 1) seed votes from /Bills into data/votes.json
      - name: Seed votes from Bills
        run: node scripts/seed-votes-from-bills.mjs

      # 2) members.json
      - name: Pull members
        run: node scripts/pull-members.mjs

      # 3) roll-call offenders (only affects bills that have congress+roll fields)
      - name: Pull votes (offenders)
        run: node scripts/pull-votes.mjs
        env:
          CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}

      # 4) donors/receipts aggregates
      - name: Pull donors/receipts
        run: node scripts/pull-donors.mjs
        env:
          FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
          CYCLE: "2026"

      # 5) build alignment index
      - name: Build alignments
        run: node scripts/build-alignments.mjs

      # 6) sanity check
      - name: Validate
        run: npm run validate || true

      # 7) commit only if data changed
      - name: Commit refreshed data
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          git diff --quiet --cached || git commit -m "refresh data"
          git push
