name: Refresh data
on:
  workflow_dispatch:
  schedule:
    - cron: '17 9 * * *'   # daily 09:17 UTC

permissions:
  contents: write   # <-- lets the workflow commit JSON files

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # If you have package.json, uncomment the next line:
      # - run: npm ci

      # Pull members
      - name: Pull members
        run: node scripts/pull-members.mjs

      # Fill offenders from real roll calls (uses votes.json "rc")
      - name: Pull votes
        run: node scripts/pull-votes.mjs
        env:
          CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}

      # Donor aggregates (skips if no secret)
      - name: Pull donors
        if: ${{ secrets.FEC_API_KEY != '' }}
        run: node scripts/pull-donors.mjs
        env:
          FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
          CYCLE: 2026

      # Build simple alignment score (tolerant if you haven't added it yet)
      - name: Build alignments
        run: node scripts/build-alignments.mjs || true

      - name: Commit refreshed data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          git diff --cached --quiet || git commit -m "refresh data"
          git push
