name: Refresh data
on:
  workflow_dispatch:
  schedule:
    - cron: '17 9 * * *'   # 09:17 UTC daily
permissions:
  contents: write
jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}
      FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
      CYCLE: 2026
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci || npm i
      - name: Pull members
        run: node scripts/pull-members.mjs
      - name: Pull votes
        run: node scripts/pull-votes.mjs
      - name: Pull donors
        run: node scripts/pull-donors.mjs
      - name: Build alignments
        run: node scripts/build-alignments.mjs
      - name: Commit refreshed data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          git diff --cached --quiet || git commit -m "refresh data"
          git push
